name: RPG_Fight_Simulator_workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall main.cpp character.h character.cpp
      - run: chmod +x ./runfile.sh 
      - run: diff output.txt goodoutput.txt
      