name: RPG_Fight_Simulator_workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall main.cpp character.h character.cpp -o a
      - run: sh ./runfile.sh a output.txt
      - run: diff output.txt goodoutput.txt
      