name: RPG_Fight_Simulator_workflow

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall main.cpp character.h character.cpp -o run
      - run: chmod +x ./runfile.sh run output.txt
      - run: diff output.txt goodoutput.txt
      